ChieuTour/Models/Tour.cs
namespace ChieuTour.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web.Mvc;

    [Table("Tour")]
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }

        [Key]
        public int MaTour { get; set; }

        [Required(ErrorMessage = "Tên tour không được để trống!")]
        [DisplayName("Tên tour")]
        [StringLength(500)]
        public string TenTour { get; set; }

        [Required(ErrorMessage = "Mô tả không được để trống!")]
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }
        [AllowHtml]
        [Required(ErrorMessage = "Lịch trình không được để trống!")]
        [DisplayName("Lịch trình")]
        public string LichTrinh { get; set; }

        [Required(ErrorMessage = "Giá người lớn không được để trống!")]
        [DisplayName("Giá người lớn")]
        [Column(TypeName = "money")]
        [Range(0, 1000000000, ErrorMessage = "Giá phải lớn hơn 0")]
        public decimal GiaNL { get; set; }

        [Required(ErrorMessage = "Giá trẻ em không được để trống!")]
        [DisplayName("Giá trẻ em")]
        [Column(TypeName = "money")]
        [Range(0, 1000000000, ErrorMessage = "Giá phải lớn hơn 0")]
        public decimal GiaTE { get; set; }

        [Required(ErrorMessage = "Phương tiện không được để trống!")]
        [DisplayName("Phương tiện")]
        [StringLength(200)]
        public string PhuongTien { get; set; }

        [DisplayName("Ảnh")]
        [StringLength(500)]
        public string Anh { get; set; }

        [DisplayName("Danh mục tour")]
        public int MaDanhMuc { get; set; }

        [Required(ErrorMessage = "Giảm giá không được để trống!")]
        [DisplayName("Giảm giá")]
        [Range(0, 100, ErrorMessage = "Giảm giá 0 - 100")]

        public int GiamGia { get; set; }

        [Required(ErrorMessage = "Hoạt động không được để trống!")]
        [DisplayName("Hoạt động")]
        [StringLength(50)]
        public string HoatDong { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }

        public virtual DanhMuc DanhMuc { get; set; }
    }
}

ChieuTour/Areas/Admin/Controllers/ToursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChieuTour.Models;

namespace ChieuTour.Areas.Admin.Controllers
{
    public class ToursController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();

        // GET: Admin/Tours
        public ActionResult Index()
        {
            var tours = db.Tours.Include(t => t.DanhMuc);
            return View(tours.ToList());
        }

        // GET: Admin/Tours/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // GET: Admin/Tours/Create
        public ActionResult Create()
        {
            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc");
            return View();
        }

        // POST: Admin/Tours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTour,TenTour,MoTa,LichTrinh,GiaNL,GiaTE,PhuongTien,Anh,MaDanhMuc,GiamGia,HoatDong")] Tour tour, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                string fileName = System.IO.Path.GetFileName(image.FileName);
                string urlImage = Server.MapPath("~/wwwroot/images/" + fileName);
                image.SaveAs(urlImage);

                tour.Anh = fileName;
            }

            if (ModelState.IsValid)
            {
                db.Tours.Add(tour);
                db.SaveChanges();
                TempData["success"] = "Thêm tour thành công!";
                return RedirectToAction("Index");
            }

            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc", tour.MaDanhMuc);
            return View(tour);
        }

        // GET: Admin/Tours/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc", tour.MaDanhMuc);
            return View(tour);
        }

        // POST: Admin/Tours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTour,TenTour,MoTa,LichTrinh,GiaNL,GiaTE,PhuongTien,Anh,MaDanhMuc,GiamGia,HoatDong")] Tour tour, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {

                if (tour != null)
                {
                    if (image != null && image.ContentLength > 0)
                    {
                        string fileName = System.IO.Path.GetFileName(image.FileName);
                        string urlImage = Server.MapPath("~/wwwroot/images/" + fileName);
                        image.SaveAs(urlImage);

                        tour.Anh = fileName;
                    }
                }

                db.Entry(tour).State = EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Sửa tour thành công!";
                return RedirectToAction("Index");
            }
            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc", tour.MaDanhMuc);
            return View(tour);
        }

        // GET: Admin/Tours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tour tour = db.Tours.Find(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // POST: Admin/Tours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tour tour = db.Tours.Find(id);
            db.Tours.Remove(tour);
            db.SaveChanges();
            TempData["success"] = "Xóa tour thành công!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChieuTour/Controllers/TourController.cs
using ChieuTour.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChieuTour.Controllers
{
    public class TourController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        // GET: Tour
        public ActionResult Detail(int id)
        {
            Tour tour = db.Tours.Find(id);

            return View(tour);
        }
    }
}

ChieuTour/Areas/Admin/Views/Tours/Create.cshtml
@model ChieuTour.Models.Tour

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>Thêm mới</h2>

@using (Html.BeginForm("Create", "Tours", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tour</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenTour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LichTrinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">  
                
                @Html.TextAreaFor(model => model.LichTrinh, new {  @class = "ckeditor" })            
                @Html.ValidationMessageFor(model => model.LichTrinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaNL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaNL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaNL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaTE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaTE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaTE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhuongTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhuongTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhuongTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<img src="~/wwwroot/images/h0.png" alt="Ảnh" width="180" height="200" id="output" class="img-rounded" />
                    <p><label for="ufile" style="cursor: pointer">Chọn file ảnh</label></p>
                    <input type="file" name="ImageFile" id="ufile" style="display: none" onchange="loadFile(event)" />*@

                <img src="~/wwwroot/images/h0.png" alt="Ảnh" width="180" height="200" id="output" class="img-rounded" /><br />
                <label for="Image" style="cursor: pointer">Chọn file ảnh</label>
                <input type="file" name="Image" id="Image" style="display: none" onchange="loadFile(event)" />

                @*@Html.EditorFor(model => model.Anh, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDanhMuc, "Danh mục tour", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaDanhMuc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiamGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiamGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiamGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoatDong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoatDong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoatDong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index", "", new { @class = "btn btn-dark" })
</div>

<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>

ChieuTour/Areas/Admin/Views/Tours/Delete.cshtml
@model ChieuTour.Models.Tour

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var ImagePath = "~/wwwroot/images/" + Model.Anh;
}

<h2>Xóa</h2>

<h3>Bạn muốn xóa tour này?</h3>
<div>
    <h4>Thông tin tour</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.TenDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.TenDanhMuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenTour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LichTrinh)
        </dt>

        <dd>
            @Html.Raw(Model.LichTrinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaNL)
        </dt>

        <dd>
            @string.Format("{0:0,0}", Model.GiaNL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaTE)
        </dt>

        <dd>
            @string.Format("{0:0,0}", Model.GiaTE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhuongTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhuongTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            <img src="@Url.Content(ImagePath)" alt="Ảnh" width="180" height="200" id="output" class="img-rounded" /><br />
            @Html.DisplayFor(model => model.Anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiamGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiamGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoatDong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoatDong)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Xóa" class="btn btn-danger" /> |
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-dark" })
</div>
    }
</div>

ChieuTour/Areas/Admin/Views/Tours/Details.cshtml
@model ChieuTour.Models.Tour

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <h4>Tour</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.TenDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.TenDanhMuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenTour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LichTrinh)
        </dt>

        <dd>
            @Html.Raw(Model.LichTrinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaNL)
        </dt>

        <dd>
            @string.Format("{0:0,0}", Model.GiaNL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaTE)
        </dt>

        <dd>
            @string.Format("{0:0,0}", Model.GiaTE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhuongTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhuongTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            @{
                string ImagePath = "~/wwwroot/images/" + Model.Anh;
            }
            <img src="@Url.Content(ImagePath)" width="100" class="img-responsive" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiamGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiamGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoatDong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoatDong)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaTour }, new { @class = "btn btn-warning" }) |
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-dark" })
</p>

ChieuTour/Areas/Admin/Views/Tours/Edit.cshtml
@model ChieuTour.Models.Tour

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var ImagePath = "~/wwwroot/images/" + Model.Anh;
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm("Edit", "Tours", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tour</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaTour)

        <div class="form-group">
            @Html.LabelFor(model => model.TenTour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LichTrinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.LichTrinh, new { @class = "ckeditor"})
                @Html.ValidationMessageFor(model => model.LichTrinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaNL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaNL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaNL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaTE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaTE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaTE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhuongTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhuongTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhuongTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(ImagePath)" alt="Ảnh" width="180" height="200" id="output" class="img-rounded" /><br />
                <label for="Image" style="cursor: pointer">Chọn file ảnh</label>
                <input type="file" name="Image" id="Image" style="display: none" onchange="loadFile(event)" />
                @Html.EditorFor(model => model.Anh, new { htmlAttributes = new { @class = "form-control", @style = "display: none" } })
                @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDanhMuc, "Danh mục tour", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaDanhMuc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiamGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiamGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiamGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoatDong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoatDong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoatDong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-dark" })
</div>

<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>

ChieuTour/Areas/Admin/Views/Tours/Index.cshtml
@model IEnumerable<ChieuTour.Models.Tour>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Danh sách tour</h2>

<div class="text-right">

    <a class="btn btn-primary" href="/Admin/Tours/Create">
        <i class="bi bi-plus-lg btn-w"></i>&nbsp;
        Thêm tour mới
    </a>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="test" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.TenTour)
                            </th>                                                    
                            <th>
                                @Html.DisplayNameFor(model => model.GiaNL)
                            </th>                                                    
                            <th>
                                @Html.DisplayNameFor(model => model.Anh)
                            </th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenTour)
                                </td>                              
                                <td>
                                    @string.Format("{0:0,0}", item.GiaNL)
                                </td>                              
                                <td>
                                    @{
                                        string ImagePath = "~/wwwroot/images/" + item.Anh;
                                    }
                                    <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" />
                                    <br />
                                </td>
                                <td>
                                    @Html.ActionLink(" ", "Details", new { id = item.MaTour }, new { @class = "bi bi-ticket-detailed-fill btn btn-primary" }) |
                                    @Html.ActionLink(" ", "Edit", new { id = item.MaTour }, new { @class = "bi bi-pencil-square btn btn-warning" }) |
                                    @Html.ActionLink(" ", "Delete", new { id = item.MaTour }, new { @class = "bi bi-trash-fill btn btn-danger" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#test').DataTable({
            "language": {
                "paginate": {
                    "previous": "Trước",
                    "next": "Tiếp theo"
                },

            },
            "oLanguage": {
                "sEmptyTable": "Không có tour",
                "sZeroRecords": "Không bản ghi nào được tìm thấy",
                "sInfo": "Hiển thị từ _START_ đến _END_ trong số _TOTAL_ bản ghi",
                "sInfoEmpty": "Hiển thị từ 0 đến 0 trong số 0 bản ghi",
                "sInfoFiltered": "(được lọc từ _MAX_ bản ghi)",
                "sLoadingRecords": "Đang tải...",
                "sProcessing": "Đang xử lý...",
                "sSearch": "Tìm kiếm:",
            },
            lengthChange: false
        });
    });
</script>