ChieuTour/Models/DanhMuc.cs
namespace ChieuTour.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DanhMuc")]
    public partial class DanhMuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMuc()
        {
            Tours = new HashSet<Tour>();
        }

        [Key]
        public int MaDanhMuc { get; set; }

        [Required(ErrorMessage = "Tên danh mục không được để trống!")]
        [DisplayName("Tên danh mục")]
        [StringLength(500)]
        public string TenDanhMuc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
    }
}

ChieuTour/Areas/Admin/Controllers/DanhMucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChieuTour.Models;

namespace ChieuTour.Areas.Admin.Controllers
{
    public class DanhMucsController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();

        // GET: Admin/DanhMucs
        public ActionResult Index()
        {
            return View(db.DanhMucs.ToList());
        }

        // GET: Admin/DanhMucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/DanhMucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDanhMuc,TenDanhMuc")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.DanhMucs.Add(danhMuc);
                db.SaveChanges();
                TempData["success"] = "Thêm danh mục thành công!";
                return RedirectToAction("Index");
            }

            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDanhMuc,TenDanhMuc")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(danhMuc).State = EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Sửa danh mục thành công!";
                return RedirectToAction("Index");
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            try
            {
                
                db.DanhMucs.Remove(danhMuc);
                db.SaveChanges();
                TempData["success"] = "Đã xóa danh mục!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Không thể xóa danh mục này!";
                return View(danhMuc);
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChieuTour/Controllers/DanhMucController.cs
using ChieuTour.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace ChieuTour.Controllers
{
    public class DanhMucController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        // GET: DanhMuc
        public ActionResult Index(int id, int? page)
        {
            var listTours = db.Tours.Where(t => t.MaDanhMuc == id);
            listTours = listTours.OrderBy(t => t.MaTour);
            int pageSize = 6;
            int pageNumber = page ?? 1;

            return View(listTours.ToPagedList(pageNumber, pageSize));
        }
        
        public ActionResult ListDanhMuc()
        {
            var danhMucs = db.DanhMucs.ToList();
            ViewBag.danhMucTour = danhMucs;

            return PartialView("_DanhMuc");
        }

    }
}

ChieuTour/Controllers/NguoiDungController.cs
using ChieuTour.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChieuTour.Controllers
{
    public class NguoiDungController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        // GET: NguoiDung
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                var nguoiDung = db.Database.SqlQuery<User>($"loginCustomer '{tendn}', '{matkhau}'").ToList();
                if (nguoiDung.Count() > 0)
                {
                    NguoiDung kh = db.NguoiDungs.SingleOrDefault(n => n.TaiKhoan == tendn && n.MatKhau == matkhau);
                    TempData["success"] = "Đăng nhập thành công";
                    Session["TaiKhoan"] = kh;
                    Session["Tendangnhap"] = kh.HoTen;
                    return RedirectToAction("Index", "Home");
                }
                else TempData["error"] = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }

        public ActionResult Detail()
        {
            NguoiDung nguoiDung = (NguoiDung)Session["TaiKhoan"];

            return View(nguoiDung);
        }
        public ActionResult Edit()
        {
            NguoiDung nguoiDung = (NguoiDung)Session["TaiKhoan"];

            return View(nguoiDung);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NguoiDung nguoiDung, string matKhauXacNhan)
        {
            if (nguoiDung.MatKhau == matKhauXacNhan)
            {
                db.Entry(nguoiDung).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Cập nhật thông tin thành công!";
                Session["TaiKhoan"] = nguoiDung;
                Session["Tendangnhap"] = nguoiDung.HoTen;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["error"] = "Mật khẩu bạn nhập không đúng!";
            }
            return View(nguoiDung);
        }

        public ActionResult logout()
        {
            Session["Tendangnhap"] = null;

            return RedirectToAction("Index", "Home");
        }
        public ActionResult changePassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult changePassword(string oldPass, string newPass, string confirmPass)
        {
            NguoiDung nguoiDungChange = (NguoiDung)Session["TaiKhoan"];
            NguoiDung nguoiDung = db.NguoiDungs.Where(n => n.MaNguoiDung == nguoiDungChange.MaNguoiDung).FirstOrDefault();

            if (oldPass != nguoiDung.MatKhau)
            {
                TempData["error"] = "Mật khẩu cũ không chính xác!";
                return View();
            }
            else if (newPass != confirmPass)
            {
                TempData["error"] = "Mật khẩu mới bạn nhập không trùng nhau!";
                return View();
            }
            else if (nguoiDung.MatKhau == oldPass)
            {
                nguoiDung.MatKhau = newPass;
                db.Entry(nguoiDung).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                Session["TaiKhoan"] = nguoiDung;
                TempData["success"] = "Đổi mật khẩu thành công!";
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

ChieuTour/Controllers/TinTucController.cs
using ChieuTour.Models;
using PagedList;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChieuTour.Controllers
{
    public class TinTucController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        // GET: TinTuc
        public ActionResult Index(int? page)
        {
            var tinTucs = db.TinTucs.Select(t => t);
            tinTucs = tinTucs.OrderBy(t => t.MaTinTuc);

            int pageSize = 6;
            int pageNumber = page ?? 1;

            return View(tinTucs.ToPagedList(pageNumber, pageSize));           
        }
        public ActionResult Detail(int id)
        {
            var tinTuc = db.TinTucs.Find(id);

            return View(tinTuc);
        }
    }
}

ChieuTour/Views/Shared/Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/wwwroot/Admin/vendor/jquery/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/wwwroot/Admin/vendor/jquery/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}
@if (TempData["info"] != null)
{
    <script src="~/wwwroot/Admin/vendor/jquery/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.info('@TempData["info"]');
    </script>
}

ChieuTour/Views/Shared/_DanhMuc.cshtml
<div id="sidebar" class="span3" style="height: 100vh">
    <ul id="sideManu" class="nav nav-tabs nav-stacked">
        <li class="subMenu open">
            <a> DANH MỤC TOUR </a>
            <ul>
                @foreach (var item in ViewBag.danhMucTour)
                {
                    <li><a href="@Url.Action("Index", "DanhMuc", new { id = item.MaDanhMuc })">@item.TenDanhMuc</a></li>
                }
            </ul>
        </li>
    </ul>
    <br />
</div>

ChieuTour/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ChieuTour/Views/Shared/_LayoutClient.cshtml
@*@using ChieuTour.Models*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Hạnh phúc ở mỗi hành trình</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--Less styles -->
    <!-- Other Less css file //different less files has different color scheam
     <link rel="stylesheet/less" type="text/css" href="~/wwwroot/Client/themes/less/simplex.less">
     <link rel="stylesheet/less" type="text/css" href="~/wwwroot/Client/themes/less/classified.less">
     <link rel="stylesheet/less" type="text/css" href="~/wwwroot/Client/themes/less/amelia.less">  MOVE DOWN TO activate
     -->
    <!--<link rel="stylesheet/less" type="text/css" href="~/wwwroot/Client/themes/less/bootshop.less">
    <script src="~/wwwroot/Client/themes/js/less.js" type="text/javascript"></script> -->
    <!-- Bootstrap style -->
    <link id="callCss" rel="stylesheet" href="~/wwwroot/Client/themes/bootshop/bootstrap.min.css" media="screen" />
    <link href="~/wwwroot/Client/themes/css/base.css" rel="stylesheet" media="screen" />
    <!-- Bootstrap style responsive -->
    <link href="~/wwwroot/Client/themes/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="~/wwwroot/Client/themes/css/font-awesome.css" rel="stylesheet" type="text/css">
    <!-- Google-code-prettify -->
    <link href="~/wwwroot/Client/themes/js/google-code-prettify/prettify.css" rel="stylesheet" />
    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="~/esy-048237037.jpg">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/wwwroot/Client/themes/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/wwwroot/Client/themes/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/wwwroot/Client/themes/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/wwwroot/Client/themes/images/ico/apple-touch-icon-57-precomposed.png">

    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />

    <style type="text/css" id="enject"></style>
</head>
<body>
    <div id="header">
        <div class="container">
            <div id="welcomeLine" class="row">
                <div class="span6">
                    @if (Session["Tendangnhap"] != null)
                    {
                    <a href="@Url.Action("Detail", "NguoiDung")">
                        <span>Chảo mừng! @Session["Tendangnhap"]</span>
                    </a>


                    }
                </div>

                <div class="span6">
                    <div class="pull-right">
                        @*<a href="product_summary.html"><span class="">Fr</span></a>
                            <a href="product_summary.html"><span class="">Es</span></a>
                            <span class="btn btn-mini">En</span>
                            <a href="product_summary.html"><span>&pound;</span></a>
                            <span class="btn btn-mini">$155.00</span>
                            <a href="product_summary.html"><span class="">$</span></a>*@
                        <a href="@Url.Action("GioHang", "GioHang")"><span class="btn btn-mini btn-primary"><i class="icon-shopping-cart icon-white"></i>Giỏ hàng</span> </a>
                    </div>
                </div>
            </div>
            <!-- Navbar ================================================== -->
            <div id="logoArea" class="navbar">
                <a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-inner">
                    <a class="brand" href="@Url.Action("Index", "Home")"><img src="~/wwwroot/images/lg.png" style="width: 193px; height: 47px" alt="Bootsshop" /></a>
                    @using (Html.BeginForm("search", "Home", FormMethod.Get, new { @class = "form-inline navbar-search" }))
                    {
                        <input name="SearchString" type="text" placeholder="Nhập tên tour cần tìm" value="@ViewBag.Filter" required oninvalid="this.setCustomValidity('Vui lòng nhập tên tour cần tìm kiếm!')" oninput="setCustomValidity('')" />
                        <input type="submit" value="Tìm kiếm" class="btn btn-primary" />
                    }
                    <ul id="topMenu" class="nav pull-right">
                        <li class=""><a href="@Url.Action("Index", "Home")">TRANG CHỦ</a></li>
                        <li class=""><a href="@Url.Action("About", "Home")">GIỚI THIỆU</a></li>
                        <li class=""><a href="@Url.Action("Index", "TinTuc")">TIN TỨC</a></li>
                        @if (Session["Tendangnhap"] != null)
                        {
                            <li class="">
                                <a href="@Url.Action("logout", "NguoiDung")" role="button" data-toggle="modal" style="padding-right:0"><span class="btn btn-large btn-success">ĐĂNG XUẤT</span></a>
                            </li>
                        }
                        else
                        {
                            <li class="">
                                <a href="@Url.Action("Index", "NguoiDung")" role="button" data-toggle="modal" style="padding-right:0"><span class="btn btn-large btn-success">ĐĂNG NHẬP</span></a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End====================================================================== -->
    <div id="mainBody">
        <div class="container">
            <div class="row">
                <!-- Sidebar ================================================== -->
                @*@{Html.RenderAction("ListDanhMuc", "DanhMuc");}*@
                <!-- Sidebar end=============================================== -->
                @Html.Partial("Notifications")
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- Footer ================================================================== -->
    <div id="footerSection">
        <div class="container">
            <div class="row">
                <div class="span3">
                    <h5>LIÊN HỆ</h5>
                    <p>
                        Công ty TNHH Du Lịch Chiêu
                    </p>
                    <p>
                        GPKD số 0313615107do Sở KH và ĐT TP Hồ Chí Minh cấp ngày 13/01/2016
                    </p>
                    <p>
                        GĐ/Sở hữu website Đỗ Văn Triển
                    </p>
                    <p>Địa chỉ: 03 Nguyễn Văn Lượng, P 17, Q. Gò Vấp, Tp. Hồ Chí Minh</p>
                    <p>Hotline: (028) 22.37.00.77</p>
                    <p>Di động/zalo/viber: 0909.909.872</p>
                    <p>Email: chieutour@gmail.com</p>
                </div>
                <div class="span3">
                    <h5>VỀ CHÚNG TÔI</h5>
                    <p>Chiêu tour ra đời với mong muốn quảng bá và giới thiệu sản phẩm du lịch đến tất cả du khách trong và ngoài nước. Đồng thời đưa du khách đến những vùng đất đẹp nhất trong và ngoài nước. Bên cạnh việc tổ chức tour du lích thuần tuý, Chiêu Tour còn kèm các hoạt động Teambuilding, Gala Dinner, Lửa trại cho các tổ chức cty khi tham gia với Chiêu tour</p>
                </div>
                <div class="span3">
                </div>
                <div id="socialMedia" class="span3 pull-right">
                    <h5>MẠNG XÃ HỘI </h5>
                    <a href="#"><img width="60" height="60" src="~/wwwroot/Client/themes/images/facebook.png" title="facebook" alt="facebook" /></a>
                    <a href="#"><img width="60" height="60" src="~/wwwroot/Client/themes/images/twitter.png" title="twitter" alt="twitter" /></a>
                    <a href="#"><img width="60" height="60" src="~/wwwroot/Client/themes/images/youtube.png" title="youtube" alt="youtube" /></a>
                </div>
            </div>
            <p class="pull-right">&copy; ChieuTour</p>
        </div><!-- Container End -->
    </div>
    <!-- Placed at the end of the document so the pages load faster ============================================= -->
    <script src="~/wwwroot/Client/themes/js/jquery.js" type="text/javascript"></script>
    <script src="~/wwwroot/Client/themes/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/wwwroot/Client/themes/js/google-code-prettify/prettify.js"></script>

    <script src="~/wwwroot/Client/themes/js/bootshop.js"></script>
    <script src="~/wwwroot/Client/themes/js/jquery.lightbox-0.5.js"></script>
</body>
</html>

ChieuTour/Views/Shared/_Slidebar.cshtml
<div id="carouselBlk">
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
            <div class="item active">
                <div class="container">
                    <a href="@Url.Action("Index", "DanhMuc", new { id = 2 })"><img style="width:100%" src="~/wwwroot/images/slidebar1.png" alt="special offers" /></a>
                    <div class="carousel-caption">
                        <h4>Second Thumbnail label</h4>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="@Url.Action("Index", "DanhMuc", new { id = 2 })"><img style="width:100%" src="~/wwwroot/images/slidebar2.png" alt="" /></a>
                    <div class="carousel-caption">
                        <h4>Second Thumbnail label</h4>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="@Url.Action("Index", "DanhMuc", new { id = 2 })"><img style="width:100%" src="~/wwwroot/images/slidebar3.png" alt="" /></a>
                    <div class="carousel-caption">
                        <h4>Second Thumbnail label</h4>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div>

                </div>
            </div>
            </div>
            
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
</div>