ChieuTour/Models/TinTuc.cs
namespace ChieuTour.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web.Mvc;

    [Table("TinTuc")]
    public partial class TinTuc
    {
        [Key]
        public int MaTinTuc { get; set; }

        [Required(ErrorMessage = "Tiêu đề không được để trống")]
        [DisplayName("Tiêu đề")]
        [StringLength(200)]
        public string TieuDe { get; set; }

        [Required(ErrorMessage = "Nội dung không được để trống")]
        [DisplayName("Nội dung")]
        [AllowHtml]
        public string NoiDung { get; set; }

        [StringLength(200)]
        [DisplayName("Hình ảnh")]
        public string HinhAnh { get; set; }

        [Column(TypeName = "date")]
        [DisplayName("Ngày đăng")]
        public DateTime? NgayDang { get; set; }

        public int? MaNguoiDung { get; set; }

        public virtual NguoiDung NguoiDung { get; set; }
    }
}

ChieuTour/Areas/Admin/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChieuTour.Models;

namespace ChieuTour.Areas.Admin.Controllers
{
    public class TinTucsController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();

        // GET: Admin/TinTucs
        public ActionResult Index()
        {
            var tinTucs = db.TinTucs.Include(t => t.NguoiDung);
            return View(tinTucs.ToList());
        }

        // GET: Admin/TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "TaiKhoan");
            return View();
        }

        // POST: Admin/TinTucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTinTuc,TieuDe,NoiDung,HinhAnh,NgayDang,MaNguoiDung")] TinTuc tinTuc, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                string fileName = System.IO.Path.GetFileName(image.FileName);
                string urlImage = Server.MapPath("~/wwwroot/images/" + fileName);
                image.SaveAs(urlImage);

                tinTuc.HinhAnh = fileName;
            }

            if (ModelState.IsValid)
            {
                tinTuc.MaNguoiDung = 2;
                tinTuc.NgayDang = DateTime.Now;
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                TempData["success"] = "Thêm tin tức thành công!";
                return RedirectToAction("Index");
            }

            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "TaiKhoan", tinTuc.MaNguoiDung);
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "TaiKhoan", tinTuc.MaNguoiDung);
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTinTuc,TieuDe,NoiDung,HinhAnh,NgayDang,MaNguoiDung")] TinTuc tinTuc, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (tinTuc != null)
                {
                    if (image != null && image.ContentLength > 0)
                    {
                        string fileName = System.IO.Path.GetFileName(image.FileName);
                        string urlImage = Server.MapPath("~/wwwroot/images/" + fileName);
                        image.SaveAs(urlImage);

                        tinTuc.HinhAnh = fileName;
                    }
                }
                tinTuc.MaNguoiDung = 2;
                db.Entry(tinTuc).State = EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Sửa tin tức thành công!";
                return RedirectToAction("Index");
            }
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "TaiKhoan", tinTuc.MaNguoiDung);
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            TempData["success"] = "Đã xóa tin tức!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChieuTour/Controllers/TinTucController.cs
using ChieuTour.Models;
using PagedList;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChieuTour.Controllers
{
    public class TinTucController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        // GET: TinTuc
        public ActionResult Index(int? page)
        {
            var tinTucs = db.TinTucs.Select(t => t);
            tinTucs = tinTucs.OrderBy(t => t.MaTinTuc);

            int pageSize = 6;
            int pageNumber = page ?? 1;

            return View(tinTucs.ToPagedList(pageNumber, pageSize));           
        }
        public ActionResult Detail(int id)
        {
            var tinTuc = db.TinTucs.Find(id);

            return View(tinTuc);
        }
    }
}

ChieuTour/Areas/Admin/Views/TinTucs/Create.cshtml
@model ChieuTour.Models.TinTuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm mới</h2>

@using (Html.BeginForm("Create", "TinTucs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TinTuc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TieuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.NoiDung, new { @class = "ckeditor" })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="~/wwwroot/images/h0.png" alt="Ảnh" width="180" height="200" id="output" class="img-rounded" /><br />
                <label for="Image" style="cursor: pointer">Chọn file ảnh</label>
                <input type="file" name="Image" id="Image" style="display: none" onchange="loadFile(event)" />
                @*@Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.NgayDang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNguoiDung, "MaNguoiDung", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNguoiDung", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNguoiDung, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index", "", new { @class = "btn btn-dark" })
</div>

<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>

ChieuTour/Areas/Admin/Views/TinTucs/Delete.cshtml
@model ChieuTour.Models.TinTuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var ImagePath = "~/wwwroot/images/" + Model.HinhAnh;
}

<h2>Xóa</h2>

<h3>Bạn có muốn xóa tin tức này?</h3>
<div>
    <h4>Tin tức</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Người đăng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiDung.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TieuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.Raw(Model.NoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            <img src="@Url.Content(ImagePath)" alt="Ảnh" width="180" height="200" id="output" class="img-rounded" /><br />
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDang)
        </dt>

        <dd>
            @string.Format("{0:dd/MM/yyyy}", Model.NgayDang).ToString()
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-dark" })
        </div>
    }
</div>

ChieuTour/Areas/Admin/Views/TinTucs/Details.cshtml
@model ChieuTour.Models.TinTuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <h4>Tin tức</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Người đăng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiDung.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TieuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.Raw(Model.NoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @{
                string ImagePath = "~/wwwroot/images/" + Model.HinhAnh;
            }
            <img src="@Url.Content(ImagePath)" width="100" class="img-responsive" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDang)
        </dt>

        <dd>
            @string.Format("{0:dd/MM/yyyy}", Model.NgayDang).ToString()
            @*@Html.DisplayFor(model => model.NgayDang)*@
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaTinTuc }, new { @class = "btn btn-warning" }) |
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-dark" })
</p>

ChieuTour/Areas/Admin/Views/TinTucs/Edit.cshtml
@model ChieuTour.Models.TinTuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var ImagePath = "~/wwwroot/images/" + Model.HinhAnh;
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm("Edit", "TinTucs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tin tức</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaTinTuc)

        <div class="form-group">
            @Html.LabelFor(model => model.TieuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.NoiDung, new { @class = "ckeditor" })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(ImagePath)" alt="Ảnh" width="180" height="200" id="output" class="img-rounded" /><br />
                <label for="Image" style="cursor: pointer">Chọn file ảnh</label>
                <input type="file" name="Image" id="Image" style="display: none" onchange="loadFile(event)" />
                @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control", @style = "display: none" } })

                @*@Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            
            <div class="col-md-10">
                @Html.HiddenFor(model => model.NgayDang, new { htmlAttributes = new { @class = "form-control" } })
                
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.MaNguoiDung, "MaNguoiDung", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNguoiDung", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNguoiDung, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index", null, new { @class = "btn btn-dark" })
</div>

<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>

ChieuTour/Areas/Admin/Views/TinTucs/Index.cshtml
@model IEnumerable<ChieuTour.Models.TinTuc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Tin tức</h2>

<div class="text-right">

    <a class="btn btn-primary" href="/Admin/TinTucs/Create">
        <i class="bi bi-plus-lg btn-w"></i>&nbsp;
        Thêm tin tức mới
    </a>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="test" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.TieuDe)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.HinhAnh)
                            </th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TieuDe)
                            </td>
                            <td>
                                @{
                                    string ImagePath = "~/wwwroot/images/" + item.HinhAnh;
                                }
                                <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" />
                            </td>
                            <td>
                                @Html.ActionLink(" ", "Details", new { id = item.MaTinTuc }, new { @class = "bi bi-ticket-detailed-fill btn btn-primary" }) |
                                @Html.ActionLink(" ", "Edit", new { id = item.MaTinTuc }, new { @class = "bi bi-pencil-square btn btn-warning" }) |
                                @Html.ActionLink(" ", "Delete", new { id = item.MaTinTuc }, new { @class = "bi bi-trash-fill btn btn-danger" })
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#test').DataTable({
            "language": {
                "paginate": {
                    "previous": "Trước",
                    "next": "Tiếp theo"
                },

            },
            "oLanguage": {
                "sEmptyTable": "Không có tin tức",
                "sZeroRecords": "Không bản ghi nào được tìm thấy",
                "sInfo": "Hiển thị từ _START_ đến _END_ trong số _TOTAL_ bản ghi",
                "sInfoEmpty": "Hiển thị từ 0 đến 0 trong số 0 bản ghi",
                "sInfoFiltered": "(được lọc từ _MAX_ bản ghi)",
                "sLoadingRecords": "Đang tải...",
                "sProcessing": "Đang xử lý...",
                "sSearch": "Tìm kiếm:",
            },
            lengthChange: false
        });
    });
</script>