ChieuTour/Areas/Admin/Controllers/HomeController.cs
using ChieuTour.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChieuTour.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        // GET: Admin/Home
        public ActionResult Index()
        {
            var danhMuc = db.DanhMucs.Select(d => d).Count();
            var tour = db.Tours.Select(t => t).Count();
            var donHang = db.DonHangs.Where(d => d.TinhTrang == "Đã xác nhận").Select(d => d).Count();
            var tinTuc = db.TinTucs.Select(tt => tt).Count();

            ViewBag.DanhMuc = danhMuc;
            ViewBag.Tour = tour;
            ViewBag.DonHang = donHang;
            ViewBag.TinTuc = tinTuc;


            var notification = db.DonHangs.Where(d => d.TinhTrang.Equals("Đang xử lý")).Select(d => d);
            if (notification.Count()!= 0)
            {
                TempData["info"] = "Có " + notification.Count() + " đơn hàng mới đang chờ xử lý";

            }

            //var khaibao = new SqlParameter("@nam", 2022);


            if (Session["HoTen"] == null)
            {
                return RedirectToAction("Login");
            }
            return View();
        }
        public ActionResult GetReportByYear(int year)
        {
            var thongKe = db.Database.SqlQuery<ThongKe>($"thongKe {year}").ToList();

            return Json(thongKe, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(User user)
        {
            if (ModelState.IsValid)
            {
                //var nguoiDungs = db.NguoiDungs.Where(n => n.TaiKhoan.Equals(user.TaiKhoan) && n.MatKhau.Equals(user.MatKhau) && n.IdQuyen == 1);
                var nguoiDung = db.Database.SqlQuery<User>($"loginAdmin '{user.TaiKhoan}', '{user.MatKhau}'").ToList();
                if (nguoiDung.Count() > 0)
                {
                    var nguoiDungR = db.NguoiDungs.Where(n => n.TaiKhoan.Equals(user.TaiKhoan));
                    Session["HoTen"] = nguoiDungR.FirstOrDefault().HoTen;
                    //TempData["success"] = "Đăng nhập thành công!";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Tên đăng nhập hoặc mật khẩu không chính xác");
                }
            }
            return View();
        }
        public ActionResult Logout()
        {
            Session["HoTen"] = null;
            //TempData["success"] = "Đăng xuất thành công!";
            return RedirectToAction("Index");
        }

    }
}

ChieuTour/Controllers/DanhMucController.cs
using ChieuTour.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace ChieuTour.Controllers
{
    public class DanhMucController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        // GET: DanhMuc
        public ActionResult Index(int id, int? page)
        {
            var listTours = db.Tours.Where(t => t.MaDanhMuc == id);
            listTours = listTours.OrderBy(t => t.MaTour);
            int pageSize = 6;
            int pageNumber = page ?? 1;

            return View(listTours.ToPagedList(pageNumber, pageSize));
        }
        
        public ActionResult ListDanhMuc()
        {
            var danhMucs = db.DanhMucs.ToList();
            ViewBag.danhMucTour = danhMucs;

            return PartialView("_DanhMuc");
        }

    }
}

ChieuTour/Controllers/HomeController.cs
using ChieuTour.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChieuTour.Controllers
{
    public class HomeController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        public ActionResult Index()
        {
            var kq = (from k in db.Tours
                      let tongsl = (from c in db.ChiTietDonHangs
                                    join t in db.Tours
                                    on c.MaTour equals t.MaTour
                                    where c.MaTour == k.MaTour
                                    select c.SoLuongTE + c.SoLuongNL).Sum()
                      orderby tongsl descending
                      select new ViewModel
                      {
                          tour = k
                      }).Take(6);

            ViewBag.top6 = kq;
            var listTT = db.TinTucs.Select(t => t).OrderByDescending(t => t.NgayDang).Take(4);
            ViewBag.TT = listTT;
            return View();

        }

        public ActionResult search(string searchString, int? page, string filter, decimal? min, decimal? max)
        {
            var result = db.Tours.Where(t => t.TenTour.Contains(searchString));
            int pageSize = 6;
            int pageNumber = page ?? 1;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = filter;
            }
            ViewBag.Filter = searchString;

            if (min != null && max != null)
            {
                page = 1;
                result = db.Tours.Where(t => t.GiaNL <= max && t.GiaNL >= min && t.TenTour.Contains(searchString));

            }
            ViewBag.Min = min;
            ViewBag.Max = max;

            result = result.OrderBy(r => r.MaTour);



            return View(result.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ChieuTour/Controllers/TinTucController.cs
using ChieuTour.Models;
using PagedList;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChieuTour.Controllers
{
    public class TinTucController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        // GET: TinTuc
        public ActionResult Index(int? page)
        {
            var tinTucs = db.TinTucs.Select(t => t);
            tinTucs = tinTucs.OrderBy(t => t.MaTinTuc);

            int pageSize = 6;
            int pageNumber = page ?? 1;

            return View(tinTucs.ToPagedList(pageNumber, pageSize));           
        }
        public ActionResult Detail(int id)
        {
            var tinTuc = db.TinTucs.Find(id);

            return View(tinTuc);
        }
    }
}

ChieuTour/Controllers/TourController.cs
using ChieuTour.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChieuTour.Controllers
{
    public class TourController : Controller
    {
        private ChieuTourDBContext db = new ChieuTourDBContext();
        // GET: Tour
        public ActionResult Detail(int id)
        {
            Tour tour = db.Tours.Find(id);

            return View(tour);
        }
    }
}

ChieuTour/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<div class="span2"></div>
<div class="span8 well">
    <h1 style="margin: 0px; padding: 0px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); font-size: 13px; border: 0px; outline: 0px; vertical-align: baseline; font-family: arial; line-height: 21px;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: xx-large; vertical-align: baseline; color: rgb(255, 0, 0); background: transparent;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 32px; vertical-align: baseline; background: transparent;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-family: &quot;times new roman&quot;, times; background: transparent;">C&Ocirc;NG TY DU LỊCH CHI&Ecirc;U&nbsp;TOUR</span></strong></span>
    </h1>
    <p style="margin: 0px; padding: 0px; line-height: 21px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; font-family: arial;">
        &nbsp;
    </p>
    <p style="margin: 0px; padding: 0px; line-height: 21px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; font-family: arial;">
        <span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0); font-family: Poppins, sans-serif; font-size: 14px;">GIỚI THIỆU CHI&Ecirc;U TOUR</span>
    </p>
    <p style="margin: 0px 0px 10px; padding: 0px 0px 10px; line-height: 24px; text-align: justify; box-sizing: border-box; outline: none; color: rgb(51, 51, 51); font-family: Poppins, sans-serif; font-size: 14px;">
        <span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(255, 0, 0);">Chi&ecirc;u Tour</span><span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(0, 0, 255);">&nbsp;( CTY TNHH DU LỊCH CHI&Ecirc;U ) được th&agrave;nh lập bởi 05 th&agrave;nh vi&ecirc;n đam m&ecirc; v&agrave; nhiều kinh nghiệm trong việc tổ chức du lịch .</span>
    </p>
    <p style="margin: 0px 0px 10px; padding: 0px 0px 10px; line-height: 24px; text-align: justify; box-sizing: border-box; outline: none; color: rgb(51, 51, 51); font-family: Poppins, sans-serif; font-size: 14px;">
        <span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(255, 0, 0);">Chi&ecirc;u tour</span><span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(0, 0, 255);">&nbsp;ra đời với mong muốn quảng b&aacute; v&agrave; giới thiệu sản phẩm du lịch đến tất cả du kh&aacute;ch trong v&agrave; ngo&agrave;i nước. Đồng thời đưa du kh&aacute;ch đến những v&ugrave;ng đất đẹp nhất trong v&agrave; ngo&agrave;i nước.</span>
    </p>
    <p style="margin: 0px 0px 10px; padding: 0px 0px 10px; line-height: 24px; text-align: justify; box-sizing: border-box; outline: none; color: rgb(51, 51, 51); font-family: Poppins, sans-serif; font-size: 14px;">
        <span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(0, 0, 255);">B&ecirc;n cạnh việc tổ chức tour du l&iacute;ch thuần tu&yacute; ,&nbsp;</span><span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(255, 0, 0);">Chi&ecirc;u tour</span><span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(0, 0, 255);">&nbsp;c&ograve;n k&egrave;m c&aacute;c hoạt động Teambuilding , Gala Dinner , Lửa trại cho c&aacute;c tổ chức cty khi tham gia với Chi&ecirc;u tour .</span>
    </p>
    <p style="margin: 0px 0px 10px; padding: 0px 0px 10px; line-height: 24px; text-align: justify; box-sizing: border-box; outline: none; color: rgb(51, 51, 51); font-family: Poppins, sans-serif; font-size: 14px;">
        <span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(0, 0, 255);">Với phương hướng kh&aacute;ch h&agrave;ng l&agrave; tr&ecirc;n hết . Ch&uacute;ng t&ocirc;i muốn đem lại c&aacute;c gi&aacute; trị tốt nhất cho qu&yacute; kh&aacute;ch .</span>
    </p>
    <p style="margin: 0px 0px 10px; padding: 0px 0px 10px; line-height: 24px; text-align: justify; box-sizing: border-box; outline: none; color: rgb(51, 51, 51); font-family: Poppins, sans-serif; font-size: 14px;">
        <span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(0, 0, 255);">H&atilde;y đến với Chi&ecirc;u tour ch&uacute;ng t&ocirc;i sẽ gửi đến cho qu&yacute; kh&aacute;ch những gi&aacute; trị đ&iacute;ch thực nhất .</span>
    </p>
    <p style="margin: 0px 0px 10px; padding: 0px 0px 10px; line-height: 24px; text-align: justify; box-sizing: border-box; outline: none; color: rgb(51, 51, 51); font-family: Poppins, sans-serif; font-size: 14px;">
        <span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(0, 128, 0);">Trải qua quá trình hoạt đ&ocirc;̣ng cty Chi&ecirc;u tour đã được T&ocirc;̉ng Cục Du Lịch chứng nh&acirc;̣n gi&acirc;́y phép lữ hành qu&ocirc;́c t&ecirc;́&nbsp;</span><span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; font-weight: 700;"><span style="margin: 0px; padding: 0px; box-sizing: border-box; outline: none; color: rgb(255, 0, 0);">s&ocirc;́ GP/No:79-856/2018/CTDL LHQT</span></span>
    </p>
    <p style="margin: 0px; padding: 0px; line-height: 21px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; font-family: arial;">
        &nbsp;
    </p>
    <p style="margin: 0px; padding: 0px; line-height: 21px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; font-family: arial;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: medium; vertical-align: baseline; color: rgb(255, 0, 255); font-family: &quot;times new roman&quot;, times; background: transparent;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background: transparent;">LI&Ecirc;N HỆ 24/7</strong></span>
    </p>
    <p style="margin: 0px; padding: 0px; line-height: 21px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; font-family: arial;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; text-decoration-line: underline; background: transparent;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; color: rgb(255, 0, 0); background: transparent;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: medium; vertical-align: baseline; font-family: &quot;times new roman&quot;, times; background: transparent;">Địa chỉ văn ph&ograve;ng tại Tp. Hồ Ch&iacute; Minh:</span></strong></span></span>
    </p>
    <p style="margin: 0px; padding: 0px; line-height: 21px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; font-family: arial;">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; color: rgb(0, 128, 0); text-align: center; background: transparent;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: medium; vertical-align: baseline; font-family: &quot;times new roman&quot;, times; background: transparent;">03 Nguyễn Văn Lượng, P 17, Q. G&ograve; Vấp, Tp. Hồ Ch&iacute; Minh</span></strong>
    </p>
    <p style="margin: 0px; padding: 0px; line-height: 21px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; font-family: arial;">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: medium; vertical-align: baseline; color: rgb(0, 128, 0); font-family: &quot;times new roman&quot;, times; background: transparent;">Hotline:<strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background: transparent;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent;">&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">(08) 22.37.00.77- (08) 62.57.66.81</span></span></strong></strong>
    </p>
    <h1 style="margin: 0px; padding: 0px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); font-size: 13px; border: 0px; outline: 0px; vertical-align: baseline; font-family: arial; line-height: 21px;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: x-large; vertical-align: baseline; background: transparent;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: medium; vertical-align: baseline; color: rgb(0, 128, 0); font-family: &quot;times new roman&quot;, times; background: transparent;"><strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background: transparent;">Di động/zalo/viber:&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">0909.909.872</span>&nbsp;</strong></strong></span>
    </h1>
    <p style="margin: 0px; padding: 0px; line-height: 21px; text-align: justify; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(50, 50, 50); border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; font-family: arial;">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: medium; vertical-align: baseline; color: rgb(0, 128, 0); font-family: &quot;times new roman&quot;, times; background: transparent;">Email:&nbsp;<span style="margin: 0px; padding: 0px; color: rgb(255, 0, 0);">chieutour@gmail.com</span></strong>
    </p>



</div>

ChieuTour/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ChieuTour/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutClient1.cshtml";
}

<div class="span9">
    <div class="well well-small">
        <h4>Tin tức mới</h4>
        <div class="row-fluid">
            <div id="featured" class="carousel slide">
                <div class="carousel-inner">
                    <div class="item active">
                        <ul class="thumbnails">
                            @foreach (var item in ViewBag.TT)
                            {
                                <li class="span3">
                                    <div class="thumbnail">
                                        <i class="tag"></i>
                                        <a href="@Url.Action("Detail", "TinTuc", new { @id = item.MaTinTuc })"><img src="~/wwwroot/images/@item.HinhAnh" alt="@item.HinhAnh"></a>
                                        <div class="caption">
                                            <h5>@item.TieuDe</h5>
                                            <h4><a class="btn" href="@Url.Action("Detail", "TinTuc", new { @id = item.MaTinTuc })">XEM</a></h4>
                                        </div>
                                    </div>
                                </li>

                            }
                        </ul>
                    </div>

                </div>
            </div>
        </div>
        </div>
            <h4>THỊNH HÀNH </h4>
            <ul class="thumbnails">
                @foreach (var item in ViewBag.top6)
                {
                    <li class="span3">
                        <div class="thumbnail">
                            <a href="@Url.Action("Detail", "Tour", new { id = item.tour.MaTour })"><img src="~/wwwroot/images/@item.tour.Anh" alt="" style="width:260px; height:250px" /></a>
                            <div class="caption">
                                <h5>@item.tour.TenTour</h5>
                                @if (item.tour.GiamGia != 0)
                                {
                                    double giaGiam = 0;
                                    giaGiam = (float)item.tour.GiaNL * (1 - ((float)item.tour.GiamGia / 100));
                                    @*<p style="text-decoration-line: line-through">@string.Format("{0:#,#}", item.tour.GiaNL) vnđ</p>*@
                                    <p style="color: red; font-size: large; font-weight: bold">@string.Format("{0:#,#}", giaGiam) vnđ</p>

                                }
                                else
                                {
                                    
                                    <p style="color: red; font-size: large; font-weight: bold">@string.Format("{0:#,#}", item.tour.GiaNL) vnđ</p>
                                }


                            <h4 style="text-align:center">
                                <a class="btn" href="@Url.Action("Detail", "Tour", new { id = item.tour.MaTour })"> <i class="icon-zoom-in"></i></a> 
                                @if (item.tour.HoatDong == "Đang hoạt động")
                                {
                                    <a class="btn" href="@Url.Action("ThemGiohang", "GioHang", new { @maTour = item.tour.MaTour, @strURL = Request.Url.ToString() })">
                                        Thêm vào giỏ hàng <i class="icon-shopping-cart"></i>
                                    </a>
                                }
                                else
                                {
                                    <a class="btn" style="display: none" href="@Url.Action("ThemGiohang", "GioHang", new { @maTour = item.tour.MaTour, @strURL = Request.Url.ToString() })">
                                        Thêm vào giỏ hàng <i class="icon-shopping-cart"></i>
                                    </a>
                                }
                            </h4>
                            </div>
                        </div>
                    </li>
                }

            </ul>
</div>

ChieuTour/Views/Home/search.cshtml
@model PagedList.IPagedList<ChieuTour.Models.Tour>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "search";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

@{Html.RenderAction("ListDanhMuc", "DanhMuc");}
<ul class="thumbnails">
    @if (Model.Count == 0)
    {
        <h1 class="span9">Không tìm thấy kết quả!</h1>
    }
    else
    {
        using (Html.BeginForm("search", "Home", FormMethod.Get, new { @class = "form-inline navbar-search" }))
        {
            <div class="span9">
                <input name="searchString" type="hidden" value="@ViewBag.Filter" />
                Tìm theo khoảng giá từ
                <input type="text" name="min" value="@ViewBag.Min" /> đến
                <input type="text" name="max" value="@ViewBag.Max" />
                <input type="submit" value="Tìm" />
            </div>
        }
    }
    @foreach (var item in Model)
    {
        <li class="span3">
            <div class="thumbnail">
                <a href="@Url.Action("Detail", "Tour", new { id = item.MaTour })"><img src="~/wwwroot/images/@item.Anh" alt="" style="width:260px; height:250px"/></a>
                <div class="caption">
                    <h5>@item.TenTour</h5>
                    @if (item.GiamGia != 0)
                    {
                        double giaGiam = 0;
                        giaGiam = (float)item.GiaNL * (1 - ((float)item.GiamGia / 100));
                        @*<p style="text-decoration-line: line-through">@string.Format("{0:#,#}", item.GiaNL)</p>*@
                        <p style="color: red; font-size: large; font-weight: bold">@string.Format("{0:#,#}", giaGiam) vnđ</p>

                    }
                    else
                    {
                        <p style="color: red; font-size: large; font-weight: bold">@string.Format("{0:#,#}", item.GiaNL) vnđ</p>
                    }


                <h4 style="text-align:center">
                    <a class="btn" href="@Url.Action("Detail", "Tour", new { id = item.MaTour })"> <i class="icon-zoom-in"></i></a> @if (item.HoatDong == "Đang hoạt động")
                    {
                        <a class="btn" href="@Url.Action("ThemGiohang", "GioHang", new { @maTour = item.MaTour, @strURL = Request.Url.ToString() })">
                            Thêm vào giỏ hàng <i class="icon-shopping-cart"></i>
                        </a>
                    }
                    else
                    {
                        <a class="btn" style="display: none" href="@Url.Action("ThemGiohang", "GioHang", new { @maTour = item.MaTour, @strURL = Request.Url.ToString() })">
                            Thêm vào giỏ hàng <i class="icon-shopping-cart"></i>
                        </a>
                    }
</div>
            </div>
        </li>
    }
</ul>
<div style="float: right">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("search", new { page, filter = ViewBag.Filter, min = ViewBag.Min, max = ViewBag.Max }))
</div>